name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  checks:
    name: Project Checks
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.20.x

      - name: Set env
        shell: bash
        run: |
          echo "GOPATH=${{ github.workspace }}" >> $GITHUB_ENV
          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH

      - uses: actions/checkout@v3
        with:
          path: src/github.com/containerd/nri
          fetch-depth: 25

      - uses: containerd/project-checks@v1
        with:
          working-directory: src/github.com/containerd/nri

  linters:
    name: Linters
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    strategy:
      matrix:
        go: [1.19.x, 1.20.x]
        os: [ubuntu-22.04]

    steps:
      - uses: actions/checkout@v3
        with:
          path: src/github.com/containerd/nri

      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Set env
        shell: bash
        run: |
          echo "GOPATH=${{ github.workspace }}" >> $GITHUB_ENV
          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH

      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.51.2
          working-directory: src/github.com/containerd/nri

  tests:
    name: Tests
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    strategy:
      matrix:
        go: [1.19.x, 1.20.x]

    steps:
      - uses: actions/checkout@v3
        with:
          path: src/github.com/containerd/nri

      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Set env
        shell: bash
        run: |
          echo "GOPATH=${{ github.workspace }}" >> $GITHUB_ENV
          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH

      - run: |
          make install-ginkgo test codecov
        working-directory: src/github.com/containerd/nri
